package exception.runtime.step4.test;

/*
 * Runtime 계열의 Exception
 * ArithmeticException
 * 분모를 0으로 나누려고 할 때 발생  
 */
public class RuntimeExceptionTest4 {
	public static void main(String[] args) {
		System.out.println("==========ArithmeticException ==========");
		int i = 0;
		int j = 10;
		try {
			System.out.println(j / i);
		} catch (ArithmeticException e) {
			System.out.println("분모가 0이면 안됨");
		} finally {
			System.out.println("Always Print..");
		}
	}
}